name: Release Drafter

on:
  push:
    branches:
      - main
      - dev
      - release/*
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          disable-autolabeler: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}